name: cowin_track_availability
description: A Flutter project that can track Vaccines in India using CoWIN Public APIs.

publish_to: 'none'
version: 1.2+10

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  adaptive_theme: ^2.2.0
  animations: ^2.0.0
  background_fetch: ^1.0.0
  battery_optimization: ^0.1.0
  device_apps: ^2.1.1
  expand_widget: ^2.1.0
  flutter_local_notifications: ^6.0.0
  flutter_markdown: ^0.6.2
  flutter_scroll_to_top: ^1.1.0
  flutter_speed_dial: ^3.0.5
  http: ^0.13.3
  intl: ^0.17.0
  loading_indicator: ^2.1.1
  path: ^1.8.0
  provider: ^5.0.0
  shared_preferences: ^2.0.6
  sqflite: ^2.0.0+3
  url_launcher: ^6.0.3
  in_app_review: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/vaccine.png"
  remove_alpha_ios: "true"
  adaptive_icon_background: "#ffffff"
